# Generated by Django 5.2.2 on 2025-07-23 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_is_accountant_user_is_cashier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarilgan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.treatmentregistration')),
            ],
        ),
    ]
