# Generated by Django 5.2.2 on 2025-07-24 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labregistration',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.treatmentregistration'),
        ),
    ]
