# Generated by ChatGPT on 2025-08-29
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_labregistration_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='labregistration',
            name='repeat_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
